#!/bin/bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP="$ROOT/dist/NeuroMorph Assessment.app"
CONTENTS="$APP/Contents"
RES="$CONTENTS/Resources"
rm -rf "$APP"
mkdir -p "$CONTENTS/MacOS" "$RES"
cp "$ROOT/src/Info.plist" "$CONTENTS/Info.plist"
cp "$ROOT/src/launcher.sh" "$CONTENTS/MacOS/NMA"
chmod +x "$CONTENTS/MacOS/NMA"
cp "$ROOT/src/app.py" "$RES/app.py"
cp "$ROOT/src/ui.html" "$RES/ui.html"
cp "$ROOT/src/NMAWebView.m" "$RES/NMAWebView.m"
cp "$ROOT/resources/AppIcon.png" "$RES/AppIcon.png"
cp "$ROOT/resources/AppIcon.icns" "$RES/AppIcon.icns"
cp "$ROOT/resources/NMA_VERSION.txt" "$RES/NMA_VERSION.txt"
cp "$ROOT/resources/report_template.docx" "$RES/report_template.docx"
cp "$ROOT/resources/template_background.png" "$RES/template_background.png"
echo "Built: $APP"
